# Cloudflare Worker 配置文件
# 用于部署 CORS Worker 解决 Transform API 跨域问题

name = "veo3video-image-cors"
main = "cloudflare-cors-worker.js"
compatibility_date = "2024-01-01"

# 路由配置
[[routes]]
pattern = "cdn.veo3video.me/cdn-cgi/image/*"
zone_name = "veo3video.me"

# 环境变量（如果需要）
[vars]
ENVIRONMENT = "production"

# 开发环境配置
[env.dev]
name = "veo3video-image-cors-dev"
vars = { ENVIRONMENT = "development" }

# 生产环境配置  
[env.production]
name = "veo3video-image-cors-prod"
vars = { ENVIRONMENT = "production" }