# Cloudflare CORS Worker配置
# 专门用于解决Transform API的CORS问题

name = "ai-video-cors-worker"
main = "cloudflare-cors-worker.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

# Worker服务配置
[placement]
mode = "smart"

# 路由配置
[[routes]]
pattern = "cdn.veo3video.me/cdn-cgi/image/*"
zone_name = "veo3video.me"

# 环境变量
[vars]
ENVIRONMENT = "production"
WORKER_NAME = "cors-transform-api"

# KV存储（可选，用于统计CORS请求）
# [[kv_namespaces]]
# binding = "CORS_STATS"
# id = "your-kv-namespace-id"

# 触发器配置
[triggers]
crons = []