# Cloudflare Workers/Pages 配置文件
# AI Video SaaS 项目配置

name = "ai-video-saas"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Pages 项目配置
pages_build_output_dir = "build"

# 环境变量配置
[env.production.vars]
VITE_APP_ENV = "production"

[env.preview.vars]
VITE_APP_ENV = "preview"

# KV存储绑定（如果需要）
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Durable Objects（如果需要实时功能）
# [[durable_objects.bindings]]
# name = "VIDEO_SESSIONS"
# class_name = "VideoSession"

# R2存储绑定（如果需要文件存储）
# [[r2_buckets]]
# binding = "VIDEOS"
# bucket_name = "ai-video-storage"

# 安全配置
[placement]
mode = "smart"